#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")


#! The migration job template is using the current timestamp as part of the name.
#! We don't do this here, so we need to replace the name with a static value.

#@overlay/match by=overlay.subset({"kind": "Job", "metadata": {"name": "oncall-engine-migrate"}})
---
apiVersion: batch/v1
kind: Job
metadata:
  name: oncall-engine-migrate
spec:
  template:
    metadata:
      #@overlay/replace
      name: oncall-engine-migrate