apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/rancher
  contents:
  - path: .
    helmChart:
      name: rancher
      version: 2.10.3
      repository:
        url: https://releases.rancher.com/server-charts/latest
    lazy: true
