apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/tetragon
  contents:
  - path: .
    helmChart:
      name: tetragon
      version: v1.1.2
      repository:
        url: https://helm.cilium.io
    lazy: true
