#@data/values
---
prototypes:
    - name: argocd
      kind: ytt
      repo: git
      url: https://github.com/argoproj/argo-cd
      version: v3.2.0-rc1
      includePaths:
        - manifests/install.yaml
      newRootPath: manifests
