#@data/values
---
prototypes:
    - name: argocd
      kind: ytt
      repo: git
      url: https://github.com/argoproj/argo-cd
      version: v3.0.5
      includePaths:
        - manifests/ha/install.yaml
      newRootPath: manifests/ha
