#@ load("@ytt:data","data")
#@ domain = data.values.shared.domain
#@ turn = "turn." + data.values.shared.domain
#@yaml/text-templated-strings
---
apiVersion: v1
kind: Secret
metadata:
  name: netbird
stringData:
  idpClientID: <path:static/netbird.yaml#netbird_client>
  idpClientSecret: <path:static/netbird.yaml#netbird_client_secret>
  stunServer: #@ turn
  turnServer: #@ turn
  turnServerUser: <path:static/netbird.yaml#netbird_turnServerUser>
  turnServerPassword: <path:static/netbird.yaml#netbird_turnServerPassword>
  relayPassword: <path:static/netbird.yaml#netbird_relayPassword>
  relayAddress: "rels://netbird.(@= domain @):443/relay"
  datastoreEncryptionKey: <path:static/netbird.yaml#datastoreEncryptionKey>
  #!idpServiceAccountUser: netbird/idpServiceAccountUser
  #!idpServiceAccountPassword: netbird/idpServiceAccountPassword
