#@ load("@ytt:data","data")
#@ domain = data.values.shared.domain

#@yaml/text-templated-strings
---
apiVersion: v1
kind: Secret
metadata:
  name: netbird
stringData:
  idpClientID: <path:static/netbird.yaml#netbird_client>
  idpClientSecret: <path:static/netbird.yaml#netbird_client_secret>
  stunServer: netbird/stunServer #!TODO
  turnServer: netbird/turnServer #!TODO
  turnServerUser: netbird/turnServerUser #!TODO
  turnServerPassword: <path:static/netbird.yaml#netbird_turnServerPassword>
  relayPassword: <path:static/netbird.yaml#netbird_relayPassword>
  relayAddress: "rels://netbird.(@= domain @):443/relay"
  #!idpServiceAccountUser: netbird/idpServiceAccountUser
  #!idpServiceAccountPassword: netbird/idpServiceAccountPassword
  #!datastoreEncryptionKey: netbird/datastoreEncryptionKey
