#@ load("@ytt:data","data")
#@ domain = data.values.shared.domain
---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-clients
type: Opaque
stringData:
  #@yaml/text-templated-strings
  configuration.oidc.yaml: |
    identity_providers:
      oidc:
        ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
        ## See: https://www.authelia.com/c/oidc
        cors:
          allowed_origins_from_client_redirect_uris: true
          endpoints:
            - 'userinfo'
            - 'authorization'
            - 'token'
            - 'revocation'
            - 'introspection'
        clients:
          - client_id: 'netbird'
            client_name: 'NetBird'
            client_secret: '$pbkdf2-sha256$310000$lqYOZnHS1BX7GbmUGpG.Jw$1WtqzujVFxfVbVJtSedZKAE7.erRxvu616JAgcw/4lw'
            public: false
            authorization_policy: 'two_factor'
            redirect_uris:
              - 'https://netbird.(@= domain @)/peers'
              - 'https://netbird.(@= domain @)/add-peers'
              - 'http://localhost'
            scopes:
              - 'openid'
              - 'email'
              - 'profile'
            userinfo_signed_response_alg: 'none'
            token_endpoint_auth_method: 'client_secret_post'
            jwks_uri: 'https://auth.demo.budd.ee/jwks.json'
