---
apiVersion: v1
kind: Secret
metadata:
  name: authelia
type: Opaque
stringData:
  identity_validation.reset_password.jwt.hmac.key: <path:static/authelia.yaml#identity_validation.reset_password.jwt.hmac.key>
  session.encryption.key: <path:static/authelia.yaml#session.encryption.key>
  storage.encryption.key: <path:static/authelia.yaml#storage.encryption.key>
  notifier.smtp.password.txt: <path:static/authelia.yaml#notifier.smtp.password.txt>
