apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: rabbitmq-cluster-operator
            repository:
                url: oci://registry-1.docker.io/bitnamicharts
            version: 4.4.1
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-rabbitmq-cluster-operator-4.4.1-5b0888c18f152f6e/data
      permissions: null
kind: Config
