apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/cert-manager
  contents:
  - path: .
    helmChart:
      name: cert-manager
      version: v1.17.1
      repository:
        url: https://charts.jetstack.io
    lazy: true
