apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/traefik
  contents:
  - path: .
    helmChart:
      name: traefik
      version: 34.1.0
      repository:
        url: https://traefik.github.io/charts
    lazy: true
