#@ load("@ytt:data", "data")

#@ for cluster in data.values.application.cluster:
---
apiVersion: rancher.crossplane.budd.ee/v1alpha1
kind: XCluster
metadata:
  name: #@ cluster.name
spec:
  providerConfig: #@ cluster.providerConfig

#@ end
