---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.rancher.crossplane.budd.ee
spec:
  group: rancher.crossplane.budd.ee
  names:
    kind: XCluster
    plural: xclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfig:
                  type: string
                externalNetworkId:
                  type: string
              required:
                - providerConfig
                - externalNetworkId
            status:
              type: object
              properties:
                securityGroupId:
                  type: string
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rancher-cluster
spec:
  compositeTypeRef:
    apiVersion: rancher.crossplane.budd.ee/v1alpha1
    kind: XCluster
  patchSets:
  - name: naming
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.name
  - name: providerConfig
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.providerConfig
      toFieldPath: spec.providerConfigRef.name
  resources:
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: NetworkV2
        spec:
          forProvider:
            adminStateUp: true
            description: "managed by crossplane"
            name: ""
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SubnetV2
        spec:
          forProvider:
            description: "managed by crossplane"
            name: ""
            cidr: 172.31.0.0/24
            networkIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: RouterV2
        spec:
          forProvider:
            adminStateUp: true
            externalNetworkId: ""
            description: "managed by crossplane"
            name: ""
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: RouterInterfaceV2
        spec:
          forProvider:
            description: "managed by crossplane"
            name: ""
            subnetIdSelector:
              matchControllerRef: true
            routerIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupV2
        spec:
          forProvider:
            description: "managed by crossplane"
            name: ""
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations["crossplane.io/external-name"]
          toFieldPath: status.securityGroupId
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
            description: "managed by crossplane. Internode communication"
            securityGroupId: "patch me"
            direction: ingress
            ethertype: IPv4
            remoteIpPrefix: ""
            remoteGroupId: "patch me"
          providerConfigRef:
            name: default
      patches:
      - type: PatchSet
        patchSetName: providerConfig
      - type: FromCompositeFieldPath
        fromFieldPath: status.securityGroupId
        toFieldPath: spec.forProvider.securityGroupId
      - type: FromCompositeFieldPath
        fromFieldPath: status.securityGroupId
        toFieldPath: spec.forProvider.remoteGroupId
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
            description: "managed by crossplane. Node ports"
            securityGroupId: "patch me"
            protocol: tcp
            direction: ingress
            ethertype: IPv4
            remoteIpPrefix: 0.0.0.0/0
            portRangeMin: 30000
            portRangeMax: 32767
          providerConfigRef:
            name: default
      patches:
      - type: PatchSet
        patchSetName: providerConfig
      - type: FromCompositeFieldPath
        fromFieldPath: status.securityGroupId
        toFieldPath: spec.forProvider.securityGroupId
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
            description: "managed by crossplane. SSH"
            securityGroupId: "patch me"
            protocol: tcp
            direction: ingress
            ethertype: IPv4
            remoteIpPrefix: 0.0.0.0/0
            portRangeMin: 22
            portRangeMax: 22
          providerConfigRef:
            name: default
      patches:
      - type: PatchSet
        patchSetName: providerConfig
      - type: FromCompositeFieldPath
        fromFieldPath: status.securityGroupId
        toFieldPath: spec.forProvider.securityGroupId
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
            description: "managed by crossplane. Node ports"
            securityGroupId: "patch me"
            protocol: udp
            direction: ingress
            ethertype: IPv4
            remoteIpPrefix: 0.0.0.0/0
            portRangeMin: 30000
            portRangeMax: 32767
          providerConfigRef:
            name: default
      patches:
      - type: PatchSet
        patchSetName: providerConfig
      - type: FromCompositeFieldPath
        fromFieldPath: status.securityGroupId
        toFieldPath: spec.forProvider.securityGroupId
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
            description: "managed by crossplane. K8s API server"
            securityGroupId: "patch me"
            protocol: tcp
            direction: ingress
            ethertype: IPv4
            remoteIpPrefix: 0.0.0.0/0
            portRangeMin: 6443
            portRangeMax: 6443
          providerConfigRef:
            name: default
      patches:
      - type: PatchSet
        patchSetName: providerConfig
      - type: FromCompositeFieldPath
        fromFieldPath: status.securityGroupId
        toFieldPath: spec.forProvider.securityGroupId
