---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.rancher.crossplane.budd.ee
spec:
  group: rancher.crossplane.budd.ee
  names:
    kind: XCluster
    plural: xclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              providerConfig:
                type: string
            required:
              - providerConfig
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rancher-cluster
spec:
  compositeTypeRef:
    apiVersion: rancher.crossplane.budd.ee/v1alpha1
    kind: XCluster
  resources:
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: NetworkV2
          name: network-1
        spec:
          forProvider:
            adminStateUp: true
            description: "managed by crossplane"
          providerConfigRef:
            name: openstack-shared
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SubnetV2
        metadata:
          name: subnet-1
        spec:
          forProvider:
            description: "managed by crossplane"
            cidr: 172.31.0.0/24
            networkIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: openstack-shared
