---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.rancher.crossplane.budd.ee
spec:
  group: rancher.crossplane.budd.ee
  names:
    kind: XCluster
    plural: xclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfig:
                  type: string
                externalNetworkId:
                  type: string
              required:
                - providerConfig
                - externalNetworkId
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rancher-cluster
spec:
  compositeTypeRef:
    apiVersion: rancher.crossplane.budd.ee/v1alpha1
    kind: XCluster
  patchSets:
  - name: naming
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.name
  - name: providerConfig
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.providerConfig
      toFieldPath: spec.providerConfigRef.name
  resources:
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: NetworkV2
        spec:
          forProvider:
            adminStateUp: true
            description: "managed by crossplane"
            name: ""
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SubnetV2
        spec:
          forProvider:
            description: "managed by crossplane"
            name: ""
            cidr: 172.31.0.0/24
            networkIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: RouterV2
        spec:
          forProvider:
            adminStateUp: true
            externalNetworkId: ""
            description: "managed by crossplane"
            name: ""
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: RouterInterfaceV2
        spec:
          forProvider:
            description: "managed by crossplane"
            name: ""
            subnetIdSelector:
              matchControllerRef: true
            routerIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupV2
        spec:
          forProvider:
            description: "managed by crossplane"
            name: ""
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
            description: "managed by crossplane"
            securityGroupIdSelector:
              matchControllerRef: true
            protocol: icmp
            portRangeMin: 1
            portRangeMax: 65535
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: providerConfig

    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 22
          portRangeMax: 22
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 53
          portRangeMax: 53
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 179
          portRangeMax: 179
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 6443
          portRangeMax: 6443
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 2380
          portRangeMax: 2380
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 7080
          portRangeMax: 7080
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 8472
          portRangeMax: 8472
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 8080
          portRangeMax: 8080
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 9100
          portRangeMax: 9100
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 10250
          portRangeMax: 10250
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: tcp
          portRangeMin: 30000
          portRangeMax: 32767
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SecgroupRuleV2
        spec:
          forProvider:
          description: "managed by crossplane"
          securityGroupIdSelector:
            matchControllerRef: true
          protocol: udp
          portRangeMin: 8472
          portRangeMax: 8472
          providerConfigRef:
            name: default
        patches:
        - type: PatchSet
          patchSetName: providerConfig
