---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.rancher.crossplane.budd.ee
spec:
  group: rancher.crossplane.budd.ee
  names:
    kind: XCluster
    plural: xclusters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfig:
                  type: string
                externalNetworkId:
                  type: string
              required:
                - providerConfig
                - externalNetworkId
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rancher-cluster
spec:
  compositeTypeRef:
    apiVersion: rancher.crossplane.budd.ee/v1alpha1
    kind: XCluster
  patchSets:
  - name: naming
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.name
  - name: providerConfig
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.providerConfig
      toFieldPath: spec.providerConfigRef.name
  resources:
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: NetworkV2
        spec:
          forProvider:
            adminStateUp: true
            description: "managed by crossplane"
            name: ""
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: SubnetV2
        spec:
          forProvider:
            description: "managed by crossplane"
            name: ""
            cidr: 172.31.0.0/24
            networkIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: RouterV2
        spec:
          forProvider:
            adminStateUp: true
            externalNetworkId: ""
            description: "managed by crossplane"
            name: ""
          providerConfigRef:
            name: default
    - base:
        apiVersion: networking.openstack.crossplane.io/v1alpha1
        kind: RouterInterfaceV2
        spec:
          forProvider:
            description: "managed by crossplane"
            name: ""
            subnetIdSelector:
              matchControllerRef: true
          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
    - base:
        apiVersion: compute.openstack.crossplane.io/v1alpha1
        kind: SecgroupV2
        spec:
          forProvider:
            description: "managed by crossplane"
            name: ""
            rule:
            - ipProtocol: icmp
              fromPort: 1
              toPort: 65535
            - ipProtocol: tcp
              toPort: 22
            - ipProtocol: tcp
              toPort: 53
            - ipProtocol: tcp
              toPort: 179
            - ipProtocol: tcp
              toPort: 6443
            - ipProtocol: tcp
              toPort: 2380
            - ipProtocol: tcp
              toPort: 7080
            - ipProtocol: tcp
              toPort: 8472
            - ipProtocol: tcp
              toPort: 8080
            - ipProtocol: tcp
              toPort: 9100
            - ipProtocol: tcp
              toPort: 10250
            - ipProtocol: tcp
              fromPort: 30000
              toPort: 32767
            - ipProtocol: udp
              toPort: 8472

          providerConfigRef:
            name: default
      patches:
        - type: PatchSet
          patchSetName: naming
        - type: PatchSet
          patchSetName: providerConfig
