installCRDs: true

prometheus:
  servicemonitor:
    enabled: true

replicaCount: 1
podDisruptionBudget:
  enabled: true

webhook:
  replicaCount: 1
  podDisruptionBudget:
    enabled: true

dns01RecursiveNameservers: 185.116.244.45:53,185.116.244.46:53
dns01RecursiveNameserversOnly: true

featureGates: ServerSideApply=true
