installCRDs: true

prometheus:
  servicemonitor:
    enabled: false

replicaCount: 1
podDisruptionBudget:
  enabled: true

webhook:
  replicaCount: 2
  podDisruptionBudget:
    enabled: true

dns01RecursiveNameservers: 1.1.1.1:53,8.8.8.8:53
dns01RecursiveNameserversOnly: true