apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: victoria-metrics-operator
            repository:
                url: https://victoriametrics.github.io/helm-charts/
            version: 0.42.0
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-victoria-metrics-operator-0.42.0-428bd3d4f8f8d645/data
      permissions: null
kind: Config
