#@ load("@ytt:data", "data")
---

hostname: #@ "rancher." + data.values.shared.domain

ingress:
  enabled: false
  tls:
    source: secret
bootstrapPassword: #@ data.values.application.bootstrapPassword
