---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitpod-1
spec:
  selector:
    matchLabels:
      app: gitpod-1
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: gitpod-1
    spec:
      terminationGracePeriodSeconds: 5
      initContainers:
      #! move the .openvscode-server to a shared location
      - name: share-vscode
        image: gitpod/openvscode-server:1.93.1
        volumeMounts:
        - name: openvscode-server
          mountPath: /home/openvscode-server-shared
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        command:
        - "/bin/bash"
        - "-c"
        - |
          cp -r /home/.openvscode-server /home/openvscode-server-shared/

      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /home/workspace"]
        volumeMounts:
        - name: workspace
          mountPath: /home/workspace

      containers:
      - name: vscode
        image: kbudde/tmp:openvscode-python
        volumeMounts:
        - name: openvscode-server
          mountPath: /home/.openvscode-server
          subPath: .openvscode-server
        - name: workspace
          mountPath: /home/workspace
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          limits:
            memory: "1.5Gi"
          requests:
            memory: "768Mi"
            cpu: "1"

      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: gitpod-1
      - name: openvscode-server
        emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitpod-1
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: gitpod-1
spec:
  selector:
    app: gitpod-1
  ports:
  - port: 3000
    targetPort: 3000
---
#@ load("@ytt:data", "data")
#@ domain = "s1.python." + data.values.shared.domain
#@ domainWeb = "python-web-s1." + data.values.shared.domain
#@ redirect = "https://" + domainWeb + "/?folder=/home/workspace/projects"
#@ traefikLB = "lb." + data.values.shared.domain
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitpod-1
  annotations:
    external-dns.alpha.kubernetes.io/target: #@ traefikLB
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: #@ "Host(`{}`)".format(domainWeb)
    priority: 10
    services:
      - name: gitpod-1
        port: 3000
        scheme: http
    middlewares:
    - name: gitpod-1
  - kind: Rule
    match: #@ "Host(`{}`)".format(domain)
    priority: 10
    services:
      - name: gitpod-1
        port: 3000
        scheme: http
    middlewares:
    - name: set-project
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: set-project
spec:
  redirectRegex:
    regex: ".*"
    replacement: #@ redirect
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gitpod-1
spec:
  basicAuth:
    secret: gitpod-1
---
apiVersion: v1
kind: Secret
metadata:
  name: gitpod-1
stringData:
  users: <path:static/user.yaml#s1>