apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/cloudnative-pg
  contents:
  - path: .
    helmChart:
      name: cloudnative-pg
      version: 0.22.1
      repository:
        url: https://cloudnative-pg.github.io/charts
    lazy: true
