#@ load("@ytt:data", "data")
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      values:
        branch: '{{index .metadata.labels "branch"}}'
        repo: '{{index .metadata.annotations "a8r.io/repository"}}'
        clusterName: '{{.name}}'
  template:
    metadata:
      name: '{{.values.clusterName}}'
    spec:
      project: 'default'
      source:
        repoURL: '{{.values.repo}}.git'
        targetRevision: '{{or .values.branch "HEAD" }}'
        path: 'rendered/argocd/{{slice .values.clusterName 8}}' #! drop 'cluster-' prefix
        plugin:
          name: argocd-vault-plugin
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
