#@ load("@ytt:data", "data")
base_url: #@ "oncall." + data.values.shared.domain
base_url_protocol: https


migrate:
  #! use a helm hook to manage the migration job
  useHook: true

#! Whether to install ingress controller
ingress-nginx:
  enabled: false
ingress:
  enabled: false
#! Install cert-manager as a part of the release
cert-manager:
  enabled: false

database:
  type: postgresql

#! TODO: inform upstream. It's not in the values.yaml
mariadb:
  enabled: false

#! Make sure to create the database with the following parameters:
#! CREATE DATABASE oncall WITH ENCODING UTF8;
externalPostgresql:
  host: oncall-db-rw
  port: 5432
  db_name: app
  user: app
  password:
  #! Use an existing secret for the database password
  existingSecret: oncall-db-app
  #! The key in the secret containing the database password
  passwordKey: password
  #! Extra options (see example below)
  #! Reference: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS
  options:
  #! options: >-
  #!   sslmode=verify-full
  #!   sslrootcert=/mnt/postgres-tls/ca.crt
  #!   sslcert=/mnt/postgres-tls/client.crt
  #!   sslkey=/mnt/postgres-tls/client.key


broker:
  type: rabbitmq

#! RabbitMQ is included into this release for the convenience.
#! It is recommended to host it separately from this release
#! Set rabbitmq.enabled = false and configure externalRabbitmq
rabbitmq:
  enabled: false

externalRabbitmq:
  host: oncall-queue
  port: 5672
  #! protocol:
  vhost: "/"
  #! Use an existing secret for the rabbitmq password
  existingSecret: oncall-queue-default-user
  #! The key in the secret containing the rabbitmq password
  passwordKey: password
  #! The key in the secret containing the rabbitmq username
  usernameKey: username

#! Redis is included into this release for the convenience.
#! It is recommended to host it separately from this release
#! TODO: Install valkey and disable redis
redis:
  enabled: true
  auth:
    existingSecret: oncall-redis
    existingSecretPasswordKey: redis-password
#! TODO: Install grafana and disable it here
grafana:
  enabled: true
  adminUser: admin
  adminPassword: stay-secure

prometheus:
  enabled: false

oncall:
  secrets:
    existingSecret: "oncall"
    secretKey: "SECRET_KEY"
    mirageSecretKey: "MIRAGE_SECRET_KEY"