apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: kube-prometheus-stack
            repository:
                url: https://prometheus-community.github.io/helm-charts
            version: 68.2.0
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-kube-prometheus-stack-68.2.0-c4af089bcb45145d/data
      permissions: null
kind: Config
