apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: oncall
            repository:
                url: https://grafana.github.io/helm-charts
            version: 1.15.2
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-oncall-1.15.2-9f0711a68b789f7a/data
      permissions: null
kind: Config
