apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: cloudnative-pg
            repository:
                url: https://cloudnative-pg.github.io/charts
            version: 0.23.0
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-cloudnative-pg-0.23.0-1b58e1365345b8c/data
      permissions: null
kind: Config
