apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: victoria-logs-single
            repository:
                url: https://victoriametrics.github.io/helm-charts/
            version: 0.6.5
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-victoria-logs-single-0.6.5-3ae0f7b59238277c/data
      permissions: null
kind: Config
