apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: reloader
            repository:
                url: https://stakater.github.io/stakater-charts
            version: 1.2.1
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-reloader-1.2.1-3be62d0f07f91f74/data
      permissions: null
kind: Config
