#@ load("@ytt:data", "data")
#@ domain = data.values.shared.domain
#@ frontend = "auth." + domain
#@ admin =  "keycloak." + domain
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/target: lb.demo.budd.ee
    kubernetes.io/ingress.class: traefik
  name: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: #@ "Host(`{}`)".format(frontend)
      priority: 10
      services:
        - name: keycloak-service
          port: 8080
          #! passHostHeader: true
      middlewares:
        - name: forwarded-headers
    - kind: Rule
      match: #@ "Host(`{}`)".format(admin)
      priority: 10
      services:
        - name: keycloak-service
          port: 8080
          #! passHostHeader: true
      middlewares:
        - name: forwarded-headers

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwarded-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-For: "{{ .Request.RemoteAddr }}"
      X-Real-IP: "{{ .Request.RemoteAddr }}"
