fluent-bit:
  enabled: true

server:
  #! image:
  #!   tag: v0.12.0-victorialogs
  #! -- Data retention period in month
  retentionPeriod: 1

  persistentVolume:
    enabled: true
    size: 30Gi

  config:
    #! -- Note that Host must be replaced to match your VictoriaLogs service name
    #! Default format points to VictoriaLogs service.
    outputs: |
      [OUTPUT]
          Name http
          Match kube.*
          Host {{ include "victoria-logs.server.fullname" . }}
          port 9428
          compress gzip
          uri /insert/jsonline?_stream_fields=stream,kubernetes_pod_name,kubernetes_container_name,kubernetes_namespace_name&_msg_field=log&_time_field=date
          format json_lines
          json_date_format iso8601
          header AccountID 0
          header ProjectID 0
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log On
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
      [FILTER]
          Name                nest
          Match               *
          Wildcard            pod_name
          Operation lift
          Nested_under kubernetes
          Add_prefix   kubernetes_