apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/rabbitmq-cluster-operator
  contents:
  - path: .
    helmChart:
      name: rabbitmq-cluster-operator
      version: 4.4.6
      repository:
        url: oci://registry-1.docker.io/bitnamicharts
    lazy: true
