apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/oncall
  contents:
  - path: .
    helmChart:
      name: oncall
      version: 1.13.11
      repository:
        url: https://grafana.github.io/helm-charts
    lazy: true
