#@ load("@ytt:data", "data")
---
upgradeCRDs: false

credentials:
  existingSecret: velero-s3-credentials

deployNodeAgent: true

configuration:
  features: EnableCSI

  defaultVolumesToFsBackup: #@ data.values.application.defaultVolumesToFsBackup
  backupStorageLocation:
    - name: #@ "s3-" + data.values.environment.id
      provider: aws
      bucket: velero
      prefix: #@ data.values.environment.id
      default: true
      config:
        region: fra
        s3ForcePathStyle: true
        s3Url: https://s3.es1.fra.optimist.gec.io
        checksumAlgorithm: ""
  volumeSnapshotLocation:
    - name: #@ "s3-" + data.values.environment.id
      provider: aws
      config:
        region: fra


initContainers:
  #! S3
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.0
    volumeMounts:
      - mountPath: /target
        name: plugins
