apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: rabbitmq-cluster-operator
            repository:
                url: oci://registry-1.docker.io/bitnamicharts
            version: 4.4.6
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-rabbitmq-cluster-operator-4.4.6-5afdc8c18f0b94a9/data
      permissions: null
kind: Config
