apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: local-storage
provisioner: local-provisioner
reclaimPolicy: Delete
volumeBindingMode: Immediate
