apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: ytt/argocd
  contents:
  - path: .
    git:
      url: https://github.com/argoproj/argo-cd
      ref: v2.13.3
    lazy: true
    newRootPath: manifests/ha
    includePaths:
    - manifests/ha/install.yaml
