#@ load("@ytt:data", "data")
#@ ns = data.values.myks.context.app
#@ if data.values.argocd.app.destination.namespace!="":
#@   ns = data.values.argocd.app.destination.namspace
#@ end
---
apiVersion: openstack.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: openstack-shared
spec:
  credentials:
    source: Secret
    secretRef:
      key: config
      name: openstack-shared
      namespace: #@ ns
---
apiVersion: v1
kind: Secret
metadata:
  name: openstack-shared
type: Opaque
stringData:
  config: |-
    {
      "auth_url": "<path:static/openstack.yaml#OS_AUTH_URL>",
      "application_credential_id": "<path:static/openstack.yaml#OS_APPLICATION_CREDENTIAL_ID>",
      "application_credential_secret": "<path:static/openstack.yaml#OS_APPLICATION_CREDENTIAL_SECRET>"
    }
