apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: oncall
            repository:
                url: https://grafana.github.io/helm-charts
            version: 1.13.11
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-oncall-1.13.11-d1ef1f7e89615ee/data
      permissions: null
kind: Config
