apiVersion: coroot.com/v1
kind: Coroot
metadata:
  name: coroot
spec:
  metricsRefreshInterval: 15s
  authBootstrapAdminPassword: <path:static/coroot.yaml#authBootstrapAdminPassword>

  storage:
    size: 10Gi

  prometheus:
    storage:
      size: 20Gi

  clickhouse:
    shards: 2
    replicas: 2
    storage:
      size: 50Gi

