#! This file is managed by myks
#@data/values
---
#@overlay/match-child-defaults missing_ok=True
prototypes:
    - name: kube-prometheus-stack
      kind: helm
      source: helmChart
      url: https://prometheus-community.github.io/helm-charts
      version: 59.1.0

