#@ load("@ytt:data", "data")
#@ app = data.values.application
---
kind: Secret
apiVersion: v1
metadata:
  name: flowise-config
type: Opaque
stringData:
  LOG_LEVEL: #@ app.logLevel
  #@ if app.monitoring=="prometheus":
  ENABLE_METRICS: "true"
  METRICS_PROVIDER: prometheus
  METRICS_INCLUDE_NODE_METRICS: "true"
  #@ end
