#@ load("@ytt:data", "data")
#@ app = data.values.application
#@ if/end app.monitoring=="prometheus":
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flowise
spec:
  endpoints:
    - port: http
      #! TODO: this endpoint is exposed to the world. Nothing critical but not ideal.
      path: /api/v1/metrics/
  selector:
    matchLabels:
      app.kubernetes.io/instance: flowise
      app.kubernetes.io/name: flowise
