---
apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-credentials
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=<path:static/repo.yaml#accesskey>
    aws_secret_access_key=<path:static/repo.yaml#secret>
