#@ load("@ytt:data", "data")

#@ if data.values.application.acme == "zerossl":
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: designate
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    email: #@ data.values.application.email
    privateKeySecretRef:
      name: designate-private-key-zerossl
    externalAccountBinding:
      keyID: YOUR_ZEROSSL_EAB_KEY_ID
      keySecretRef:
        name: zero-ssl-eabsecret
        key: secret
      keyAlgorithm: HS256
    solvers:
      - dns01:
          webhook:
            groupName: acme.syseleven.de
            solverName: designatedns
        selector: 
          dnsZones:
            - #@ data.values.shared.domain

---
apiVersion: v1
kind: Secret
metadata:
  name: zero-ssl-eabsecret
data:
  secret: #@ data.values.application.zerossl.eab_key_id

#@ end