#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: designate-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: #@ data.values.application.email
    privateKeySecretRef:
      name: designate-private-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.syseleven.de
            solverName: designatedns
        selector: 
          dnsZones:
            - #@ data.values.shared.domain