apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/crossplane
  contents:
  - path: .
    helmChart:
      name: crossplane
      version: 1.19.0
      repository:
        url: https://charts.crossplane.io/stable
    lazy: true
