apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: rabbitmq-cluster-operator
            repository:
                url: oci://registry-1.docker.io/bitnamicharts
            version: 4.4.2
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-rabbitmq-cluster-operator-4.4.2-5b0bc8c18f17d205/data
      permissions: null
kind: Config
