
alertmanager:
  alertmanagerSpec:
    replicas: 3
    logFormat: json
    externalUrl:
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    maxUnavailable: ""

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    #! read all selectors by default. Not just the ones defined by the chart.
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

