apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/grafana
  contents:
  - path: .
    helmChart:
      name: grafana
      version: 8.10.4
      repository:
        url: https://grafana.github.io/helm-charts
    lazy: true
