apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git: 
      repoURL: https://github.com/kbudde/k8s-demo.git
      revision: HEAD
      directories:
      - path: rendered/argocd/*
      values:
        cluster: '{{.path.basename}}'
  template:
    metadata:
      name: 'base-{{.values.cluster}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/kbudde/k8s-demo.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        plugin: 
          name: argocd-vault-plugin
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true

