apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-incluster
  namespace: argocd
---
apiVersion: v1
kind: Secret
metadata:
  name: token-argocd-incluster
  namespace: argocd
  annotations:
    kubernetes.io/service-account.name: argocd-incluster
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-incluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-incluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-incluster-role
subjects:
- kind: ServiceAccount
  name: argocd-incluster
  namespace: argocd

