#@ load("@ytt:data", "data")
#@ traefikLB = "lb." + data.values.shared.domain
---
deployment:
  replicas: 1

podDisruptionBudget:
  enabled: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: false
    publishedService:
      enabled: true

globalArguments:
- "--global.checknewversion"
#! - "--global.sendanonymoususage"
- "--entrypoints.web.http.redirections.entrypoint.scheme=https"
- "--entrypoints.web.http.redirections.entrypoint.to=websecure"

ports:
  web:
    proxyProtocol:
      trustedIPs:
        - "192.168.1.0/24"
  websecure:
    http3:
      enabled: true
      advertisedPort: 443
    proxyProtocol:
      trustedIPs:
        - "192.168.1.0/24"

experimental:
#! https://plugins.traefik.io/plugins/628c9f24ffc0cd18356a97bd/query-paramter-modification
  plugins:
    traefik-plugin-query-modification:
      moduleName: github.com/kingjan1999/traefik-plugin-query-modification
      version: v1.0.0

logs:
  general:
    level: INFO
  access:
    enabled: true

service:
  enabled: false
  #!# -- Single service is using `MixedProtocolLBService` feature gate.
  #!# -- When set to false, it will create two Service, one for TCP and one for UDP.
  single: false
  annotations:
    external-dns.alpha.kubernetes.io/hostname: #@ traefikLB
    loadbalancer.openstack.org/keep-floatingip: "true"
    loadbalancer.openstack.org/proxy-protocol: v2
    loadbalancer.openstack.org/enable-health-monitor: "true"
    loadbalancer.openstack.org/load-balancer-id: df2268f6-26b6-44c0-a62f-475855ce33c6

ingressRoute:
  dashboard:
    enabled: false
