apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: grafana
            repository:
                url: https://grafana.github.io/helm-charts
            version: 8.10.3
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-grafana-8.10.3-2e5777e5c26e80ea/data
      permissions: null
kind: Config
