#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")

#! Load values from secret

#@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "external-dns"}})
---
#@overlay/match-child-defaults missing_ok=True
spec:
  template:
    spec:
      containers:
        #@overlay/match by=overlay.map_key("name")
        - name: external-dns
          envFrom:
            - secretRef:
                name: external-dns
