apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/openstack-cloud-controller-manager
  contents:
  - path: .
    helmChart:
      name: openstack-cloud-controller-manager
      version: 2.30.1
      repository:
        url: https://kubernetes.github.io/cloud-provider-openstack
    lazy: true
