#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind": "Application"}), expects="0+"
---
#@overlay/match-child-defaults missing_ok=True
spec:
  ignoreDifferences:
  #@overlay/append
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - '.spec.template.spec.containers[].env[]?.valueFrom.resourceFieldRef.divisor'
  #! - group: monitoring.coreos.com
  #!   kind: ServiceMonitor
  #!   jqPathExpressions:
  #!     - '.spec.endpoints[]?.relabelings[]?.action'

  #! https://github.com/argoproj/argo-cd/issues/11143
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?.apiVersion'
      - '.spec.volumeClaimTemplates[]?.kind'

  #! allow manually scaling
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: apps
    kind: StatefuleSet
    jsonPointers:
    - /spec/replicas
