#@ load("@ytt:overlay", "overlay")
---
#@ def secret_fragment():
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
#@ end

#@ load("@ytt:data", "data")
#@overlay/match by=overlay.subset(secret_fragment()), expects="0+"
---
#! See https://argo-cd.readthedocs.io/en/release-2.8/operator-manual/declarative-setup/#clusters
stringData:
  config: #@ "<path:static/cluster.{id}.yaml#config>".format(id=data.values.environment.id)
  server: #@ "<path:static/cluster.{id}.yaml#server>".format(id=data.values.environment.id)

