#@ load("@ytt:data","data")
#@ domain = data.values.shared.domain

#@yaml/text-templated-strings
---
management:
  configmap: |-
    {
      "Stuns": [
        {
          "Proto": "udp",
          "URI": "{{ .STUN_SERVER }}",
          "Username": "",
          "Password": ""
        }
      ],
      "TURNConfig": {
        "TimeBasedCredentials": false,
        "CredentialsTTL": "12h0m0s",
        "Secret": "secret",
        "Turns": [
          {
            "Proto": "udp",
            "URI": "{{ .TURN_SERVER }}",
            "Username": "{{ .TURN_SERVER_USER }}",
            "Password": "{{ .TURN_SERVER_PASSWORD }}"
          }
        ]
      },
      "Relay": {
        "Addresses": ["{{ .NB_EXPOSED_ADDRESS }}"],
        "CredentialsTTL": "24h",
        "Secret": "{{ .RELAY_PASSWORD }}"
      },
      "Signal": {
        "Proto": "https",
        "URI": "{{ .NB_SIGNAL_ADDRESS }}",
        "Username": "",
        "Password": ""
      },
      "Datadir": "/var/lib/netbird/",
      "DataStoreEncryptionKey": "{{ .DATASTORE_ENCRYPTION_KEY }}",
      "HttpConfig": {
        "CertFile": "",
        "CertKey": "",
        "AuthAudience": "{{ .IDP_CLIENT_ID }}",
        "AuthIssuer": "https://idp.(@= domain @)",
        "AuthUserIDClaim": "",
        "AuthKeysLocation": "https://idp.(@= domain @)/jwks.json",
        "OIDCConfigEndpoint": "https://idp.(@= domain @)/.well-known/openid-configuration",
        "IdpSignKeyRefreshEnabled": true
      },
      "IdpManagerConfig": {},
      "DeviceAuthorizationFlow": {},
      "PKCEAuthorizationFlow": {
        "ProviderConfig": {
          "Audience": "{{ .IDP_CLIENT_ID }}",
          "ClientID": "{{ .IDP_CLIENT_ID }}",
          "ClientSecret": "{{ .IDP_CLIENT_SECRET }}",
          "Domain": "",
          "AuthorizationEndpoint": "https://idp.(@= domain @)/api/oidc/authroization/",
          "TokenEndpoint": "https://idp.(@= domain @)/api/oidc/token/",
          "Scope": "openid email profile",
          "UseIDToken": false,
          "RedirectURLs": ["http://localhost:53000"],
          "UseIDToken": true
        }
      },
      "StoreConfig": {
        "Engine": "postgres"
      },
      "ReverseProxy": {
        "TrustedHTTPProxies": null,
        "TrustedHTTPProxiesCount": 0,
        "TrustedPeers": null
      }
    }

  persistentVolume:
    enabled: false
  envFromSecret:
    NETBIRD_STORE_ENGINE_POSTGRES_DSN: netbird-db-app/uri
    STUN_SERVER: netbird/stunServer
    TURN_SERVER: netbird/turnServer
    TURN_SERVER_USER: netbird/turnServerUser
    TURN_SERVER_PASSWORD: netbird/turnServerPassword
    RELAY_PASSWORD: netbird/relayPassword
    IDP_CLIENT_ID: netbird/idpClientID
    #! IDP_SERVICE_ACCOUNT_USER: netbird/idpServiceAccountUser
    #! IDP_SERVICE_ACCOUNT_PASSWORD: netbird/idpServiceAccountPassword
    DATASTORE_ENCRYPTION_KEY: netbird/datastoreEncryptionKey
    NB_EXPOSED_ADDRESS: netbird/relayAddress
  env:
    NB_SIGNAL_ADDRESS: "netbird.(@= domain @):443"


relay:
  envFromSecret:
    NB_AUTH_SECRET: netbird/relayPassword
    NB_EXPOSED_ADDRESS: netbird/relayAddress
  env:
    NB_LOG_LEVEL: info
    NB_LISTEN_ADDRESS: ":33080"

dashboard:
  enabled: true
  env:
    #! Endpoints
    NETBIRD_MGMT_API_ENDPOINT: https://netbird.(@= domain @):443
    NETBIRD_MGMT_GRPC_API_ENDPOINT: https://netbird.(@= domain @):443
    #! OIDC
    AUTH_AUTHORITY: https://auth.(@= domain @)
    USE_AUTH0: false
    AUTH_SUPPORTED_SCOPES: openid email profile
    AUTH_REDIRECT_URI: /peers
    AUTH_SILENT_REDIRECT_URI: /add-peers
    NETBIRD_TOKEN_SOURCE: idToken
    #!NGINX_SSL_PORT:
    #!LETSENCRYPT_DOMAIN:
    #!LETSENCRYPT_EMAIL:
    AUTH_AUDIENCE: none
  envFromSecret:
    AUTH_CLIENT_ID: netbird/idpClientID
    AUTH_CLIENT_SECRET: netbird/idpClientSecret
