apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: charts/redis-cluster
  contents:
  - path: .
    helmChart:
      name: redis-cluster
      version: 11.0.6
      repository:
        url: https://charts.bitnami.com/bitnami
    lazy: true
