#@ load("@ytt:data", "data")
#@ domain = "grafana." + data.values.shared.domain
---
testFramework:
  enabled: true

serviceMonitor:
  enabled: true

ingress:
  enabled: false

persistence:
  type: pvc
  enabled: true

#! Administrator credentials when not using an existing secret (see below)
adminUser: admin
#! adminPassword: strongpassword

#! Use an existing secret for the admin user.
admin:
  #!# Name of the secret. Can be templated.
  existingSecret: "kbudde-user"
  userKey: user
  passwordKey: password

env:
  GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "victorialogs-datasource"
#!   GF_INSTALL_PLUGINS: "https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.2.1/victorialogs-datasource-v0.2.1.zip;victorialogs-datasource"

plugins:
- https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.2.1/victorialogs-datasource-v0.2.1.zip;victorialogs-datasource
- grafana-oncall-app

  #! - digrich-bubblechart-panel
  #! - grafana-clock-panel
  #!# You can also use other plugin download URL, as long as they are valid zip files,
  #!# and specify the name of the plugin after the semicolon. Like this:
  #! - https://grafana.com/api/plugins/marcusolsson-json-datasource/versions/1.3.2/download;marcusolsson-json-datasource

#!# Grafana's primary configuration
#!# NOTE: values in map will be converted to ini format
#!# ref: http://docs.grafana.org/installation/configuration/
#!#
grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: false
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: #@ domain
    root_url: #@ "https://" + domain
  feature_toggles:
    externalServiceAccounts: true
    featureToggleAdminPage: true
  feature_management:
    allow_editing: true


sidecar:
  alerts:
    enabled: true
    #! label that the configmaps with alert are marked with
    label: grafana_alert
    searchNamespace: ALL
  dashboards:
    enabled: true
    label: grafana_dashboard
    searchNamespace: ALL
  datasources:
    enabled: true
    label: grafana_datasource
    searchNamespace: ALL
  plugins:
    enabled: true
    label: grafana_plugin
    searchNamespace: ALL
  notifiers:
    enabled: true
    label: grafana_notifier
    searchNamespace: ALL

imageRenderer:
  enabled: true
  serviceMonitor:
    enabled: true

initChownData:
  securityContext:
    capabilities:
      drop:
        - NET_RAW

useStatefulSet: true