apiVersion: vendir.k14s.io/v1alpha1
directories:
    - contents:
        - helmChart:
            name: oncall
            repository:
                url: https://grafana.github.io/helm-charts
            version: 1.15.3
          lazy: true
          path: .
      path: .myks/vendir-cache/helm-oncall-1.15.3-9f040da68b7662d7/data
      permissions: null
kind: Config
