apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task
  name: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      volumes:
        - name: syncdata
          persistentVolumeClaim:
            claimName: syncdata
      containers:
      - image: ghcr.io/gothenburgbitfactory/taskchampion-sync-server:main
        name: taskchampion-sync-server
        args:
          - "--allow-client-id"
          - "465600ee-b5a5-11ef-894c-d7569779cf2c"
        imagePullPolicy: Always
        volumeMounts:
          - name: syncdata
            mountPath: /var/lib/taskchampion-sync-server
        ports:
          - name: http
            containerPort: 8080
            protocol: tcp



