apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task
  name: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: task
          persistentVolumeClaim:
            claimName: task
      containers:
      - image: ghcr.io/gothenburgbitfactory/taskchampion-sync-server:main
        name: taskchampion-sync-server
        args:
          - "--data-dir"
          - /data
          - "--allow-client-id"
          - "<path:static/taskwarrior.yaml#client-id>"
        imagePullPolicy: Always
        volumeMounts:
          - name: task
            mountPath: /data 
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP



