apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task 
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
